name: MPPU
channels:
  - menpo
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py35_0
  - bleach=1.5.0=py35_0
  - cffi=1.11.5=py35h9745a5d_0
  - chardet=3.0.4=py35hb6e9ddf_1
  - cryptography=2.2.2=py35h14c3975_0
  - cycler=0.10.0=py35hc4d5149_0
  - cython=0.28.2=py35h14c3975_0
  - dbus=1.13.2=h714fa37_1
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.56.1=h000015b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - html5lib=0.9999999=py35_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py35h8605a33_1
  - intel-openmp=2018.0.0=8
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py35hcb1117a_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=hf84eae3_0
  - markdown=2.6.11=py35_0
  - matplotlib=2.2.2=py35h0e671d2_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py35h3010b51_0
  - mkl_random=1.0.1=py35h629b387_0
  - ncurses=6.0=h9df7e31_2
  - numpy=1.14.2=py35hdbf6ddf_1
  - olefile=0.45.1=py35_0
  - pandas=0.23.0=py35h637b7d7_0
  - pcre=8.42=h439df22_0
  - pillow=5.1.0=py35h3deb7b8_0
  - pip=9.0.3=py35_0
  - protobuf=3.5.2=py35hf484d3e_0
  - pycparser=2.18=py35h61b3040_1
  - pyopenssl=17.5.0=py35h4f8b8c8_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.9.2=py35h751905a_0
  - pysocks=1.6.8=py35_0
  - python=3.5.5=hc3d631a_1
  - python-dateutil=2.7.2=py35_0
  - pytz=2018.4=py35_0
  - qt=5.9.5=h7e424d6_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py35hb9e6ad1_1
  - setuptools=39.0.1=py35_0
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35h423b573_1
  - sqlite=3.23.1=he433501_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py35_0
  - tqdm=4.23.0=py35_0
  - urllib3=1.22=py35h2ab6e29_0
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.0=py35_0
  - xz=5.2.3=h5e939de_4
  - zlib=1.2.11=ha838bed_2
  - arrow-cpp=0.10.0=py35h70250a7_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - graphite2=1.3.12=hfc679d8_1
  - jasper=1.900.1=4
  - parquet-cpp=1.5.0.pre=h83d4a3d_0
  - pixman=0.34.0=h470a237_3
  - pyarrow=0.10.0=py35hfc679d8_0
  - _nb_ext_conf=0.4.0=py35_1
  - anaconda-client=1.6.14=py35_0
  - appdirs=1.4.3=py35_0
  - attrs=18.1.0=py35_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h7636065_2
  - certifi=2018.4.16=py35_0
  - clyent=1.2.2=py35h491ffcb_1
  - constantly=15.1.0=py35_0
  - decorator=4.3.0=py35_0
  - entrypoints=0.2.3=py35h48174a2_2
  - ffmpeg=4.0=h04d0a96_0
  - gmp=6.1.2=h6c8ec71_1
  - h5py=2.8.0=py35ha1f6525_0
  - harfbuzz=1.7.6=h5f0a787_1
  - hdf5=1.10.2=hba1933b_1
  - hyperlink=18.0.0=py35_0
  - incremental=17.5.0=py35head57c3_0
  - ipykernel=4.8.2=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.3.1=py35_0
  - jedi=0.12.0=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35ha89e94b_0
  - libboost=1.65.1=habcd387_4
  - libevent=2.1.8=h93c0eb6_0
  - libopus=1.2.1=hb9ed12e_0
  - libsodium=1.0.16=h1bed415_0
  - libvpx=1.7.0=h439df22_0
  - lz4-c=1.8.1.2=h14c3975_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - mistune=0.8.3=py35h14c3975_1
  - nb_anacondacloud=1.4.0=py35_0
  - nb_conda=2.2.1=py35hccc8299_0
  - nb_conda_kernels=2.1.0=py35_0
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - nbpresent=3.0.2=py35h9c03491_1
  - notebook=5.6.0=py35_0
  - openssl=1.0.2o=h20670df_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py35h1565a15_1
  - parso=0.2.1=py35_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - prometheus_client=0.3.1=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - pyasn1=0.4.4=py35_0
  - pyasn1-modules=0.2.2=py35_0
  - pygments=2.2.0=py35h0f41973_0
  - pyyaml=3.13=py35h14c3975_0
  - pyzmq=17.1.0=py35h14c3975_0
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.1.0=py35hfc37229_0
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - snappy=1.1.7=hbae5bb6_3
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - thrift-cpp=0.11.0=hc04171f_3
  - traitlets=4.3.2=py35ha522a97_0
  - twisted=18.7.0=py35h14c3975_1
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - widgetsnbextension=3.3.1=py35_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_0
  - zope=1.0=py35_0
  - zope.interface=4.5.0=py35h14c3975_0
  - zstd=1.3.3=h84994c4_0
  - pip:
    - absl-py==0.2.0
    - astor==0.6.2
    - enum34==1.1.6
    - future==0.16.0
    - gast==0.2.0
    - grpcio==1.11.0
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - lmdb==0.94
    - openexr==1.3.2
    - plyfile==0.5
    - pydot==1.2.4
    - pyhamcrest==1.9.0
    - python-graph-core==1.8.2
    - python-graph-dot==1.8.2
    - python-prctl==1.7
    - tabulate==0.8.2
    - tensorflow==1.11.0
    - tensorflow-gpu==1.11.0
    - termcolor==1.1.0
    - transforms3d==0.3.1
prefix: /home/ywang/anaconda3/envs/tf

